/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ChatApp: typeof import('./src/components/ChatApp.vue')['default']
    ConversationInfo: typeof import('./src/components/ConversationInfo.vue')['default']
    Footer: typeof import('./src/components/Auth/Footer.vue')['default']
    Header: typeof import('./src/components/Auth/Header.vue')['default']
    IconWrapper: typeof import('./src/components/IconWrapper.vue')['default']
    Item: typeof import('./src/components/LevNav/Item.vue')['default']
    ItemChat: typeof import('./src/components/ItemChat.vue')['default']
    LeftNav: typeof import('./src/components/LevNav/LeftNav.vue')['default']
    LeftSide: typeof import('./src/components/LeftSide.vue')['default']
    Login: typeof import('./src/components/Auth/Login.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    PopupInvite: typeof import('./src/components/PopupInvite.vue')['default']
    PopupRemoveMessage: typeof import('./src/components/PopupRemoveMessage.vue')['default']
    Register: typeof import('./src/components/Auth/Register.vue')['default']
    RightSide: typeof import('./src/components/RightSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleChat: typeof import('./src/components/SingleChat.vue')['default']
    TypingAnimation: typeof import('./src/components/TypingAnimation.vue')['default']
  }
}
