/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ChatApp: typeof import('./src/components/ChatApp.vue')['default']
    ConversationInfo: typeof import('./src/components/ConversationInfo.vue')['default']
    GroupChat: typeof import('./src/components/GroupChat.vue')['default']
    IconWrapper: typeof import('./src/components/IconWrapper.vue')['default']
    Item: typeof import('./src/components/LevNav/Item.vue')['default']
    ItemChat: typeof import('./src/components/ItemChat.vue')['default']
    LeftNav: typeof import('./src/components/LevNav/LeftNav.vue')['default']
    LeftSide: typeof import('./src/components/LeftSide.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RightSide: typeof import('./src/components/RightSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleChat: typeof import('./src/components/SingleChat.vue')['default']
    TypingAnimation: typeof import('./src/components/TypingAnimation.vue')['default']
  }
}
